/*
 * MCaaS API
 *
 * APIs and object schemas for MCaaS.
 *
 * API version: v1
 * Contact: Centaur-GLHC@hpe.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package mcaasapi

type MachineImageVersions struct {
	Count int32 `json:"count,omitempty"`
	Total int32 `json:"total,omitempty"`
	Items []MachineImageVersion `json:"items,omitempty"`
}
