/*
 * HPE GreenLake for Private Cloud Containers APIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package mcaasapi

type CreateCluster struct {
	Name string `json:"name,omitempty"`
	Description string `json:"description,omitempty"`
	ClusterBlueprintId string `json:"clusterBlueprintId,omitempty"`
	ApplianceID string `json:"applianceID,omitempty"`
	SpaceID string `json:"spaceID,omitempty"`
}
