/*
 * MCaaS API
 *
 * APIs and object schemas for MCaaS.
 *
 * API version: v1
 * Contact: Centaur-GLHC@hpe.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package mcaasapi

type MachineImageVersion struct {
	Master []MachineImage `json:"master,omitempty"`
	Worker []MachineImage `json:"worker,omitempty"`
}
