/*
 * MCaaS API
 *
 * APIs and object schemas for MCaaS.
 *
 * API version: v1
 * Contact: Centaur-GLHC@hpe.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package mcaasapi

type Licenses struct {
	Label string `json:"label,omitempty"`
	Summary string `json:"summary,omitempty"`
	Status string `json:"status,omitempty"`
}
