/*
 * HPE GreenLake for Private Cloud Containers APIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package mcaasapi

type MachineRolesType string

// List of MachineRolesType
const (
	WORKER_MachineRolesType MachineRolesType = "worker"
	CONTROLPLANE_MachineRolesType MachineRolesType = "controlplane"
	ETCD_MachineRolesType MachineRolesType = "etcd"
)
