/*
 * MCaaS API
 *
 * APIs and object schemas for MCaaS.
 *
 * API version: v1
 * Contact: Centaur-GLHC@hpe.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package mcaasapi

type MachineRolesType string

// List of MachineRolesType
const (
	WORKER_MachineRolesType MachineRolesType = "worker"
	CONTROLPLANE_MachineRolesType MachineRolesType = "controlplane"
	ETCD_MachineRolesType MachineRolesType = "etcd"
)
