/*
 * HPE GreenLake for Private Cloud Containers APIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package mcaasapi

type ConflictError struct {
	HttpStatusCode int32 `json:"httpStatusCode,omitempty"`
	Message string `json:"message,omitempty"`
	DebugId string `json:"debugId,omitempty"`
	ErrorCode string `json:"errorCode,omitempty"`
}
