/*
 * MCaaS API
 *
 * APIs and object schemas for MCaaS.
 *
 * API version: v1
 * Contact: Centaur-GLHC@hpe.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package mcaasapi

type UpdateCluster struct {
	Description string `json:"description,omitempty"`
	K8sVersion string `json:"k8sVersion,omitempty"`
	MachineSets []MachineSet `json:"machineSets,omitempty"`
}
