/*
 * MCaaS API
 *
 * APIs and object schemas for MCaaS.
 *
 * API version: v1
 * Contact: Centaur-GLHC@hpe.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package mcaasapi

type MachineWorkerType string

// List of MachineWorkerType
const (
	VIRTUAL_MachineWorkerType MachineWorkerType = "Virtual"
	PHYSICAL_MachineWorkerType MachineWorkerType = "Physical"
)
