/*
 * HPE GreenLake for Private Cloud Containers APIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package mcaasapi

type Policy struct {
	Id string `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
	Description string `json:"description,omitempty"`
	Group string `json:"group,omitempty"`
	Template string `json:"template,omitempty"`
	TotalViolations int32 `json:"totalViolations,omitempty"`
	Violations []Violation `json:"violations,omitempty"`
}
