/*
 * MCaaS API
 *
 * APIs and object schemas for MCaaS.
 *
 * API version: v1
 * Contact: Centaur-GLHC@hpe.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package mcaasapi

type ClusterUtilization struct {
	AvgCpu string `json:"avgCpu,omitempty"`
	AvgMemory string `json:"avgMemory,omitempty"`
	TotalPersistentStorage string `json:"totalPersistentStorage,omitempty"`
}
