/*
 * HPE GreenLake for Private Cloud Containers APIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package mcaasapi
import (
	"time"
)

type ClusterProvider struct {
	State string `json:"state,omitempty"`
	Health string `json:"health,omitempty"`
	CreatedDate time.Time `json:"createdDate,omitempty"`
	LastUpdateDate time.Time `json:"lastUpdateDate,omitempty"`
	Id string `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
	K8sVersions []string `json:"k8sVersions,omitempty"`
	KubernetesVersions []string `json:"kubernetesVersions,omitempty"`
	MinMasterSize *AllOfClusterProviderMinMasterSize `json:"minMasterSize,omitempty"`
	MinWorkerSize *AllOfClusterProviderMinWorkerSize `json:"minWorkerSize,omitempty"`
	LicenseInfo *ClusterProviderLicenseInfo `json:"licenseInfo,omitempty"`
	StorageClasses []StorageClass `json:"storageClasses,omitempty"`
	AvailableCapacity *ClusterProviderAvailableCapacity `json:"availableCapacity,omitempty"`
}
