/*
 * HPE GreenLake for Private Cloud Containers APIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package mcaasapi

type Licenses struct {
	Label string `json:"label,omitempty"`
	Summary string `json:"summary,omitempty"`
	Status string `json:"status,omitempty"`
}
