/*
 * HPE GreenLake for Private Cloud Containers APIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package mcaasapi

type MachineSetDetail struct {
	Name string `json:"name,omitempty"`
	MachineBlueprintName string `json:"machineBlueprintName,omitempty"`
	MachineBlueprintId string `json:"machineBlueprintId,omitempty"`
	OsImage string `json:"osImage,omitempty"`
	OsVersion string `json:"osVersion,omitempty"`
	Count float64 `json:"count,omitempty"`
	MachineRoles []MachineRolesType `json:"machineRoles,omitempty"`
	MachineProvider string `json:"machineProvider,omitempty"`
	Size string `json:"size,omitempty"`
	SizeDetail *AllOfMachineSetDetailSizeDetail `json:"sizeDetail,omitempty"`
	ComputeInstanceType string `json:"computeInstanceType,omitempty"`
	StorageInstanceType string `json:"storageInstanceType,omitempty"`
	Networks []string `json:"networks,omitempty"`
	Machines []Machine `json:"machines,omitempty"`
	Tags *interface{} `json:"tags,omitempty"`
}
