/*
 * MCaaS API
 *
 * APIs and object schemas for MCaaS.
 *
 * API version: v1
 * Contact: Centaur-GLHC@hpe.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package mcaasapi

type MachineSet struct {
	Name string `json:"name,omitempty"`
	MachineBlueprintName string `json:"machineBlueprintName,omitempty"`
	MachineBlueprintId string `json:"machineBlueprintId,omitempty"`
	OsImage string `json:"osImage,omitempty"`
	OsVersion string `json:"osVersion,omitempty"`
	Count float64 `json:"count,omitempty"`
}
