/*
 * MCaaS API
 *
 * APIs and object schemas for MCaaS.
 *
 * API version: v1
 * Contact: Centaur-GLHC@hpe.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package mcaasapi
import (
	"time"
)

type Machine struct {
	State string `json:"state,omitempty"`
	Health string `json:"health,omitempty"`
	CreatedDate time.Time `json:"createdDate,omitempty"`
	LastUpdateDate time.Time `json:"lastUpdateDate,omitempty"`
	Name string `json:"name,omitempty"`
	Hostname string `json:"hostname,omitempty"`
	Id string `json:"id,omitempty"`
}
