/*
 * MCaaS API
 *
 * APIs and object schemas for MCaaS.
 *
 * API version: v1
 * Contact: Centaur-GLHC@hpe.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package mcaasapi

type SiteConsumptionConsumption struct {
	Cpu float64 `json:"cpu,omitempty"`
	Memory float64 `json:"memory,omitempty"`
	Disk float64 `json:"disk,omitempty"`
	PersistentStorage float64 `json:"persistentStorage,omitempty"`
	Clusters float64 `json:"clusters,omitempty"`
}
