/*
 * MCaaS API
 *
 * APIs and object schemas for MCaaS.
 *
 * API version: v1
 * Contact: Centaur-GLHC@hpe.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package mcaasapi
import (
	"time"
)

type ClusterProvider struct {
	State string `json:"state,omitempty"`
	Health string `json:"health,omitempty"`
	CreatedDate time.Time `json:"createdDate,omitempty"`
	LastUpdateDate time.Time `json:"lastUpdateDate,omitempty"`
	Id string `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
	K8sVersions string `json:"k8sVersions,omitempty"`
	MinMasterSize []SizeDetail `json:"minMasterSize,omitempty"`
	MinWorkerSize []SizeDetail `json:"minWorkerSize,omitempty"`
	LicenseInfo *ClusterProviderLicenseInfo `json:"licenseInfo,omitempty"`
	StorageClasses []StorageClass `json:"storageClasses,omitempty"`
	AvailableCapacity *ClusterProviderAvailableCapacity `json:"availableCapacity,omitempty"`
}
