/*
 * MCaaS API
 *
 * APIs and object schemas for MCaaS.
 *
 * API version: v1
 * Contact: Centaur-GLHC@hpe.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package mcaasapi
import (
	"time"
)

type Cluster struct {
	State string `json:"state,omitempty"`
	Health string `json:"health,omitempty"`
	CreatedDate time.Time `json:"createdDate,omitempty"`
	LastUpdateDate time.Time `json:"lastUpdateDate,omitempty"`
	Id string `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
	Description string `json:"description,omitempty"`
	ErrorCode string `json:"errorCode,omitempty"`
	ErrorMessage string `json:"errorMessage,omitempty"`
	ClusterBlueprintId string `json:"clusterBlueprintId,omitempty"`
	ClusterProvider string `json:"clusterProvider,omitempty"`
	K8sVersion string `json:"k8sVersion,omitempty"`
	KubernetesVersion string `json:"kubernetesVersion,omitempty"`
	MachineSets []MachineSet `json:"machineSets,omitempty"`
	MachineSetsDetail []MachineSetDetail `json:"machineSetsDetail,omitempty"`
	Utilization *ClusterUtilization `json:"utilization,omitempty"`
	ApiEndpoint string `json:"apiEndpoint,omitempty"`
	ServiceEndpoints []ServiceEndpoints `json:"serviceEndpoints,omitempty"`
	ApplianceID string `json:"applianceID,omitempty"`
	ApplianceName string `json:"applianceName,omitempty"`
	SpaceID string `json:"spaceID,omitempty"`
	DefaultStorageClass string `json:"defaultStorageClass,omitempty"`
	DefaultStorageClassDescription string `json:"defaultStorageClassDescription,omitempty"`
	ProviderData *ClusterProviderData `json:"providerData,omitempty"`
}
