/*
 * HPE GreenLake for Private Cloud Containers APIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package mcaasapi

type ClusterProviderAvailableCapacity struct {
	Cpu float64 `json:"cpu,omitempty"`
	Nodes float64 `json:"nodes,omitempty"`
	Clusters float64 `json:"clusters,omitempty"`
	Summary string `json:"summary,omitempty"`
}
