/*
 * HPE GreenLake for Private Cloud Containers APIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package mcaasapi

type MachineSet struct {
	Name string `json:"name,omitempty"`
	MachineBlueprintName string `json:"machineBlueprintName,omitempty"`
	MachineBlueprintId string `json:"machineBlueprintId,omitempty"`
	OsImage string `json:"osImage,omitempty"`
	OsVersion string `json:"osVersion,omitempty"`
	Count float64 `json:"count,omitempty"`
}
