/*
 * MCaaS API
 *
 * APIs and object schemas for MCaaS.
 *
 * API version: v1
 * Contact: Centaur-GLHC@hpe.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package mcaasapi

type ComputeInstanceTypes struct {
	Name string `json:"name,omitempty"`
	Sizes []SizeDetail `json:"sizes,omitempty"`
}
