/*
 * MCaaS API
 *
 * APIs and object schemas for MCaaS.
 *
 * API version: v1
 * Contact: Centaur-GLHC@hpe.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package mcaasapi

type ClusterProviderData struct {
	ServiceConsoleContext string `json:"serviceConsoleContext,omitempty"`
	ProviderClusterID string `json:"providerClusterID,omitempty"`
}
