/*
 * HPE GreenLake for Private Cloud Containers APIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package mcaasapi
import (
	"time"
)

type MachineBlueprint struct {
	CreatedDate time.Time `json:"createdDate,omitempty"`
	LastUpdateDate time.Time `json:"lastUpdateDate,omitempty"`
	Id string `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
	MachineProvider string `json:"machineProvider,omitempty"`
	WorkerType *MachineWorkerType `json:"workerType,omitempty"`
	MachineRoles []MachineRolesType `json:"machineRoles,omitempty"`
	OsImage string `json:"osImage,omitempty"`
	OsVersion string `json:"osVersion,omitempty"`
	Size string `json:"size,omitempty"`
	SizeDetail *AllOfMachineBlueprintSizeDetail `json:"sizeDetail,omitempty"`
	ComputeInstanceType string `json:"computeInstanceType,omitempty"`
	StorageInstanceType string `json:"storageInstanceType,omitempty"`
	Tags *interface{} `json:"tags,omitempty"`
	ApplianceID string `json:"applianceID,omitempty"`
}
