/*
 * HPE GreenLake for Private Cloud Containers APIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package mcaasapi
import (
	"time"
)

type ClusterBlueprint struct {
	CreatedDate time.Time `json:"createdDate,omitempty"`
	LastUpdateDate time.Time `json:"lastUpdateDate,omitempty"`
	Id string `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
	Description string `json:"description,omitempty"`
	K8sVersion string `json:"k8sVersion,omitempty"`
	KubernetesVersion string `json:"kubernetesVersion,omitempty"`
	ClusterProvider string `json:"clusterProvider,omitempty"`
	MachineSets []MachineSet `json:"machineSets,omitempty"`
	MachineSetsDetail []MachineSetDetail `json:"machineSetsDetail,omitempty"`
	ApplianceID string `json:"applianceID,omitempty"`
	DefaultStorageClass string `json:"defaultStorageClass,omitempty"`
	ControlPlaneCount int32 `json:"controlPlaneCount,omitempty"`
}
