/*
 * HPE GreenLake for Private Cloud Containers APIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package mcaasapi

type MachineWorkerType string

// List of MachineWorkerType
const (
	VIRTUAL_MachineWorkerType MachineWorkerType = "Virtual"
	PHYSICAL_MachineWorkerType MachineWorkerType = "Physical"
)
